### ISSUE TITLE
Create a new listing

### ISSUE THREAD

**Issue by gilhrpenner** [gilhrpenner/COMP4350#103]
## Description
As a registered user\
I want to create a new listing\
so that I can sell an item.

## Acceptance Criteria
- User must be logged in
- The newly created listing should be visible at the top of other listings for that category
- User must complete all mandatory fields

## Dev tasks
- [x] [Create repository for listings](https://github.com/gilhrpenner/COMP4350/issues/122)
- [x] Upload images to S3
- [ ]  [Cleanup listing endpoints and enable authentication](https://github.com/gilhrpenner/COMP4350/issues/140)
- [x] [CRUD operations for listings](https://github.com/gilhrpenner/COMP4350/issues/98)

Story points: 3/5

**Comment by MarkRobitaille** [comment]
## Manual Acceptance Test

Create a new listing
1. If you do not have an account, follow the “create an account” steps.
2. If you are not logged into your account, follow the “sign in with an account” steps.
3. Once signed in and on the dashboard page, click on the + button that is labelled with “Create a new listing” to open the new listing config dialog.
4. On the new listing config dialog, select a category from the category dropdown (example value: `Books`).
5. Select a province from the province dropdown (example value: `Manitoba`).
6. Select a city from the city dropdown (example value: `Winnipeg`). Note: This may take a moment to load in the city options as we are using an API to get the cities for a province. There will be a loading bar on the bottom of the screen to indicate once it finishes loading.
7. Click on the next button to navigate to the listing editor page.
8. Fill in the listing title field (example value: `My test listing`).
9. Fill in the price field (example value: `100.00`).
10. Select a condition from the condition dropdown. (example value: `Used - Fair`).
11. Select a status from the status dropdown (example value: `Pending`).
12. Fill in the description field (example value: `This is a test description`).
13. Click on the gray box under “Select item photos” to open the file browser to select and upload a .jpg, .jpeg, or .png image file. Note: You can select more than one photo to upload.
14. Click the create listing button to create the new listing and to navigate back to the dashboard. A notification should appear telling you you have created a new listing. Your newly created listing should be added to the dashboard.
15. Click on the paper with an eye icon button on your created listing to open a preview dialog window which displays the listing information. The information here should match what was entered.
